# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: 'https://yashminimal.in'
baseurl: ''
title: 'Blog'
description: 'ðŸ‘‹ Yash here, welcome to my home on internet.'
permalink: pretty
logo: "/images/yash-icon.PNG"
favicon: "/images/yash-icon.PNG"

# Pagination
paginate: 5
paginate_path: page:num

# Collections
collections:
  posts:
    title: yashminimal
    output: true
    description: "ðŸ‘‹ Yash here, welcome to my home on internet. Learn more about me [here](about)"

defaults:
 -
  scope:
    path: ""
    type: pages
  values:
    layout: page # Default layout
 -
  scope:
    path: ""
    type: posts
  values:
    layout: post # Default layout
